### ISSUE TITLE
Show compression levels in an ActivePivot application

### ISSUE THREAD

**Issue by OPeyrusse** [activeviam/mac#59]
ActivePivot is capable of compressing chunks, creating single-value chunks, offset chunks, etc.
This information can be viewed in MAC. Yet, there is no measure for the saved space.
Intuitively, we could compute for each chunk a measure being `chunk_size / chunk_visible_size`, giving a ratio of the saved memory.

**Comment by MehdiEnnaime** [comment]
Non-bug issues are to be tracked by the internal Jira until PIVOT-6552 is done.
