### ISSUE TITLE
Consider adding additional metadata to help reporting

### ISSUE THREAD

**Issue by SBrown52** [activeviam/mac#62]
Something I started doing a while ago and spoke to OPE about, but haven't had chance to revisit. I've decided to create an Issue to get my thoughts down so that they are not lost.

As per the title, consider adding additional metadata.

For example when I browse the cube and create a table I can see the memory impact of a store of various fields, but I don't have much information around the usage of the store of fields. It would be good to know:

* the size (number of rows) in the store - I can then create a dashboard to see how the memory usage grows with the number of records loaded in the store
* a field being dictionarised or not - you can hack around and figure this out whether it's in the cube or not, but would be nice to know from a datastore level. The idea being that I could create a table showing the memory of the system vs datastore fields and whether they are dictionarised or not. For any none cube levels, I may than to explicitly dictionarise that field and reduce memory
* Cardinality of a field - eg could be used when analysing whether it's a suitable field for a secondary index or inclusion to the aggregate providers

I will add to this if I get any more ideas.

**Comment by MehdiEnnaime** [comment]
Non-bug issues are to be tracked by the internal Jira until PIVOT-6552 is done.
