### ISSUE TITLE
Impossible to use MAC from the generated SpringBoot JAR file

### ISSUE THREAD

**Issue by obilliard** [activeviam/mac#83]
If you try to compile the SpringBoot JAR and start MAC, it fails as it cannot load the JSON files into the Content Server.
Indeed the code is set to properly pick the files contained inside the JAR (BOOT-INF/classes).
This needs to be fixed as this is not usable to always rely on running it inside the IDE.

I have prepared a fix in the branch 5.10-FIX-START-JAR.

**Comment by MehdiEnnaime** [comment]
Tracked internally by PIVOT-6606, the 5.10-FIX-START-JAR branch will likely be re-used and merged in the new `main` branch
